### ISSUE TITLE
`be_valid_markup` is throwing "HTTP error: 307"

### ISSUE THREAD

**Issue by MikeRogers0** [unboxed/be_valid_asset#19]
Using the default gem setup settings the following code:

```
require 'acceptance/acceptance_helper'

feature "be_valid_asser", acceptance: true do
  scenario "homepage has valid markup" do
    visit root_path
    expect(page).to be_valid_markup
  end
end
```

Fails with the message:

```
Failure/Error: expect(page).to be_valid_markup

     RuntimeError:
       HTTP error: 307
```

Any suggestions for a work around / what could be causing the redirect? Happy to PR if needed if anyone can point me in the right direction :)

**Comment by h-lame** [comment]
I'm guessing that the 307 is coming from `be_valid_asset` when it tries to talk to the w3c validators.  So this probably means they no longer live at the same path, or are redirecting you to a holding page as a rate-limit solution.  Check the redirect that you're getting and see where it's pointing you at - if it's just that the validators have moved, you can change the host / path used by `be_valid_asset`, but if it's a rate-limit redirect you might want to  set up your own local instance of the validator suite.

Both options have some documentation in the [README](https://github.com/unboxed/be_valid_asset#change-validator-hostpath).

If it is a redirect to a new path rather than a rate-limit problem, we could change the defaults in [`BeValidAsset::BeValidMarkup`](https://github.com/unboxed/be_valid_asset/blob/a4d2096d2b6f108c9fb06e0431bc854479a9cd1f/lib/be_valid_asset/be_valid_markup.rb#L9-L12).  We should probably also make [`BeValidAsset::BeValidBase#call_validator`](https://github.com/unboxed/be_valid_asset/blob/a4d2096d2b6f108c9fb06e0431bc854479a9cd1f/lib/be_valid_asset/be_valid_base.rb#L71-L76) be redirect aware.  If you wanted to explore those options that'd be useful.

Hope this helps.

**Comment by MikeRogers0** [comment]
Awesome! I'll investigate as to if I'm being rate limited or just redirected, then update this accordingly :)
